routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('empleados', 'EmpleadoController');

app/Empleado.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Empleado extends Model
{
    protected $fillable = [
        'nombre',
        'edad',
        'salario'
      ];

    // Mass assignment
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmpleadoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Empleado;

class EmpleadoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $empleados = Empleado::OrderBy('nombre', 'desc')->paginate(4);

        return view('empleados.index', compact('empleados'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('empleados.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nombre' => 'required',
            'edad' => 'required|integer',
            'salario' => 'required|integer'
        ]);

        $empleado = new Empleado([
            'nombre'  => $request->get('nombre'),
            'edad'    => $request->get('edad'),
            'salario' => $request->get('salario')
        ]);

        $empleado->save();
        return redirect('empleados')->with('mensaje', 'Un nuevo usuario fue agregado');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $empleado = Empleado::find($id);

        return view('empleados.edit', compact('empleado'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nombre' => 'required',
            'edad' => 'required|integer',
            'salario' => 'required|integer'
        ]);

        $empleado = Empleado::find($id);
        $empleado->nombre = $request->get('nombre');
        $empleado->edad = $request->get('edad');
        $empleado->salario = $request->get('salario');
        $empleado->save();

        return redirect('empleados')->with('mensaje', 'Empleado actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $empleado = Empleado::find($id);
        $empleado->delete();

        return redirect('empleados')->with('mensaje', 'Empleado eliminado');
    }
}

resources/views/empleados/create.blade.php
@extends('layout')
@section('content')
<style>
  .espacio {
    margin-top: 40px;
  }
  .card-header{
      background-color: #3490dc;
      color: #ffffff;
  }
</style>

<div class="card espacio">
    <div class="card-header">
        Agregar Empleado
    </div>
    <div class="card-body">
        @if($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div><br/>
        @endif
        <form action="{{ route('empleados.store')}}" method="post">
            @csrf
            <div class="form-group">
              <label for="nombre">Nombre:</label>
              <input type="text" class ="form-control" name="nombre" value="{{old('nombre')}}">
            </div>
            <div class="form-group">
              <label for="edad">Edad:</label>
              <input type="text" class ="form-control" name="edad" value="{{old('edad')}}">
            </div>
            <div class="form-group">
              <label for="salario">Salario:</label>
              <input type="text" class ="form-control" name="salario" value="{{old('salario')}}">
            </div>
            <button type="button" class="btn btn-success" onclick="window.location='{{ url("empleados")}}'">Regresar</button>
            <button type="submit" class="btn btn-primary">Agregar</button>
        </form>
    </div>
</div>
@endsection

resources/views/empleados/edit.blade.php
@extends('layout')
@section('content')
<style>
  .espacio {
    margin-top: 40px;
  }
  .card-header{
      background-color: #3490dc;
      color: #ffffff;
  }
</style>

<div class="card espacio">
    <div class="card-header">
        Editar Empleado
    </div>
    <div class="card-body">
        @if($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div><br/>
        @endif
        <form action="{{ route('empleados.update', $empleado->id) }}" method="post">
            @method('PATCH')
            @csrf
            <div class="form-group">
                <label for="nombre">Nombre: </label>
                <input type="text" class="form-control" name="nombre" value="{{ $empleado->nombre }}">
            </div> 
            <div class="form-group">
                <label for="edad">Edad: </label>
                <input type="text" class="form-control" name="edad" value="{{ $empleado->edad }}">
            </div> 
            <div class="form-group">
                <label for="salario">Salario: </label>
                <input type="text" class="form-control" name="salario" value="{{ $empleado->salario }}">
            </div>
            <button type="submit" class="btn btn-primary">Actualizar</button>           
        </form>
    </div>
</div>
@endsection

resources/views/empleados/index.blade.php
@extends('layout')
@section('content')
<style>
  .espacio{
    margin-top: 40px;
  }
</style>
<div class="espacio">
    <h1>Inventorio de Empleados</h1>
    <hr/>
    <button class="btn btn-primary" onclick="window.location='{{ route("empleados.create") }}'">Agregar un nuevo empleado</button>
    @if(session()->get('mensaje'))
        <div class="alert alert-{{ strpos(session()->get('mensaje') , 'eliminado') ? 'danger' : 'success'}}">
            {{session()->get('mensaje') }}
        </div><br/>
    @endif
    <table class="table table-striped">
        <thead>
            <tr>
                <td>ID</td>
                <td>Nombre</td>
                <td>Edad</td>
                <td>Salario</td>
                <td>Editar</td>
                <td>Borrar</td>
            </tr>
        </thead>
        <tbody>
            @foreach($empleados as $empleado)
            <tr>
                <td>{{ $empleado->id}}</td>
                <td>{{ $empleado->nombre}}</td>
                <td>{{ $empleado->edad}}</td>
                <td>{{ $empleado->salario}}</td>
                <td><a href="{{ route('empleados.edit', $empleado->id)}}" class="btn btn-primary">Editar</a></td>
                <td>
                    <form action="{{ route('empleados.destroy', $empleado->id)}}" method="post">
                    @csrf
                    @method('DELETE')
                    <button onclick = "return confirm('Estas seguro de borrar este empleado?')" class="btn btn-danger" type="submit">Borrar</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    {{ $empleados->links()}}
</div>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Inventorio</title>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="container">
        @yield('content')
    </div>
 <script src="{{ asset('js/app.js') }}" type="text/js"></script>   
</body>
</html>